#pragma once

#define SCREEN_WIDTH 500
#define SCREEN_HEIGHT 800

#define SPLASH_TIME 1
#define MODAL_WAIT_TIME 0.5

#define STATUS_DRAW 0
#define STATUS_O_WON 1
#define STATUS_X_WON 2
#define STATUS_PLAYING 3

#define PIECE_NONE 0
#define PIECE_O 1
#define PIECE_X 2

#define TURN_X 0
#define TURN_O 1

#define SCREEN_DIFFICULTY 0
#define SCREEN_CHOOSE_PIECE 1
#define SCREEN_VSCOMPUTER_GAME 2

#define DIFFICULTY_EASY 0
#define DIFFICULTY_MEDIUM 1
#define DIFFICULTY_HARD 2